/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// GroupSelectionInfo A Selection composed of a group of devices.
type GroupSelectionInfo struct {
	// Path of the directory whose devices belong to this selection
	DirectoryPath string `json:"directoryPath"`
	// Indicates whether devices from the entire subtree (true) or only direct members (false) of the given directory are included in this selection
	Recursive bool `json:"recursive,omitempty"`
	// Indicates whether only gateways are included in this selection.
	GatewaysOnly bool `json:"gatewaysOnly,omitempty"`
	// List of tag names to further narrow down the selection - only devices belonging to the given directory and tagged with the given tags are included in this selection.
	Tags []string `json:"tags,omitempty"`
	// RQL filter query which is used to narrow down the devices belonging to this selection. If present, only devices matching this query will be present in the selection.
	RqlQuery string `json:"rqlQuery,omitempty"`
	// A custom Groovy filtering script which is used to narrow down the devices belonging to this selection. If present, only devices satisfying this script will be included in the selection.
	FilteringScript string `json:"filteringScript,omitempty"`
}
