/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// GroovySelectionInfo A Dynamic selection of devices determined by a custom Groovy listing script.
type GroovySelectionInfo struct {
	// Custom Groovy listing script which dynamically includes devices in the selection
	ListingScript string `json:"listingScript"`
	// A custom Groovy filtering script which is used to narrow down the devices belonging to this selection. If present, only devices satisfying this script will be included in the selection.
	FilteringScript string `json:"filteringScript,omitempty"`
}
