/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// RuleStatusInfo struct for RuleStatusInfo
type RuleStatusInfo struct {
	// User-friendly display name of this Rule
	DisplayName string `json:"displayName"`
	// Rule identifier
	RuleId string `json:"ruleId"`
	State int32 `json:"state,omitempty"`
	StateDescription string `json:"stateDescription,omitempty"`
	// The count of involved devices with the given execution status.
	InvolvedCount int32 `json:"involvedCount"`
	// The count of involved devices with FINISHED_SUCCESS(0) status.
	SuccessCount int32 `json:"successCount,omitempty"`
	// The count of involved devices with  FINISHED_WARNING(1) status.
	WarningCount int32 `json:"warningCount,omitempty"`
	// The count of involved devices with  FINISHED_ERROR(2) status.
	ErrorCount int32 `json:"errorCount,omitempty"`
	// The count of involved devices with  FINISHED_CANCELED(3) status.
	CancelCount int32 `json:"cancelCount,omitempty"`
	TriggersCount int32 `json:"triggersCount,omitempty"`
	NextTimeTrigger int64 `json:"nextTimeTrigger,omitempty"`
	// User
	User string `json:"user,omitempty"`
	// Custom properties assigned to this Rule.
	Props []string `json:"props,omitempty"`
	Scope ScopeInfo `json:"scope"`
	Trigger TriggerInfo `json:"trigger,omitempty"`
	Options ExecOptInfo `json:"options,omitempty"`
	Action ActionInfo `json:"action"`
	FullStatus bool `json:"fullStatus,omitempty"`
}
