/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// FunctionBlock Feature definition Function Block
type FunctionBlock struct {
	Id ModelId `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Description string `json:"description,omitempty"`
	FileName string `json:"fileName,omitempty"`
	References []ModelId `json:"references,omitempty"`
	ConfigurationProperties []ModelProperty `json:"configurationProperties,omitempty"`
	StatusProperties []ModelProperty `json:"statusProperties,omitempty"`
	FaultProperties []ModelProperty `json:"faultProperties,omitempty"`
	Events []ModelEvent `json:"events,omitempty"`
	Operations []Operation `json:"operations,omitempty"`
}
