/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// TaskExecOptInfo Execution options define execution behavior of Tasks and Rules
type TaskExecOptInfo struct {
	// Restricts the maximum number of devices concurrently executing a Task or Rule.
	ConcurrencyLimit int32 `json:"concurrencyLimit"`
	// Time-schedule is permitted for the Task to act. Time schedule constraint supplied as Cron-expression. <code>Example:</code> <li/>* * 9-17 ? * MON-FRI: defines work time to be on working days (Monday to Friday) between 9.00-17.00h<li/>* * 00-01 * * ?: defines work to be time every day between 00-01 in the morning.<li/>* * * 01 * ?: defines work time to be on the 1st day of each month .
	TimeConstraint string `json:"timeConstraint"`
}
