/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// DeviceScopeInfo The JSON Schema defines three pre-filled options in this order of priority - IdSelection, GroovySelection, GroupSelection - for defining Device Scope. Only one of them should be filled in. If several options are present - even if any of them is left empty or is invalid, all of them will be considered according to their order of priority.
type DeviceScopeInfo struct {
	IdSelection IdSelectionInfo `json:"idSelection"`
	GroovySelection GroovySelectionInfo `json:"groovySelection"`
	GroupSelection GroupSelectionInfo `json:"groupSelection"`
}
