/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// TriggerElInfo Should be a groovy script that could be evaluated to boolean value <code>true</code> or <code>false</code>.
type TriggerElInfo struct {
	// A groovy script that will be executed and expected to return a boolean result or it might be a json query filter that will be matched against the Rule-fire event
	Condition string `json:"condition,omitempty"`
	TriggerEvent TriggerEventInfo `json:"triggerEvent,omitempty"`
}
