/*
 * Bosch IoT Manager API
 *
 * The Bosch IoT Manager REST API provides the full functionality of the service, including:  &middot;    Retrieving devices and features; adding and modifying device-specific properties and attributes  &middot;    A simple device registration mechanism  &middot;    All grouping capabilities - listing, creating, modifying and deleting directories and tags  &middot;    The complete mass management experience, which allows full control over tasks and rules   Find out more details in our [documentation](https://docs.bosch-iot-suite.com/manager/).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iotmgr
// ActionInfo Groovy script and type defining the action for this Rule.
type ActionInfo struct {
	// The type of action used. All available action types can be listed through the method <code>ws/mme/rules/actions</code>
	ActionType string `json:"actionType"`
	// A JSON object, which should satisfy the metadata required for this action type. The metadata for the given action type is available through the method <code>ws/mme/rules/actions/{actionType}</code>
	ActionDef string `json:"actionDef"`
}
